// Package store provides project-local SQLite-backed result storage for acap.
package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"math/rand/v2"
	"os"
	"path/filepath"
	"time"

	"github.com/taqu/agentcap/internal/project"
	"github.com/taqu/agentcap/internal/stats"
	"modernc.org/sqlite"
)

const driverName = "sqlite"

// Meta holds the metadata for a stored result.
type Meta struct {
	ID          string    `json:"id"`
	Command     []string  `json:"command"`
	ExitCode    int       `json:"exit_code"`
	StartedAt   time.Time `json:"started_at"`
	DurationMs  int64     `json:"duration_ms"`
	StdoutBytes int64     `json:"stdout_bytes"`
	StderrBytes int64     `json:"stderr_bytes"`
	Reducer     string    `json:"reducer"`
	CreatedAt   time.Time `json:"created_at"`
	Truncated   bool      `json:"truncated"`
	// Phase 3 fields (all omitempty for backwards compatibility)
	SessionID    string `json:"session_id,omitempty"`
	Sequence     int    `json:"sequence,omitempty"`
	BaselineID   string `json:"baseline_id,omitempty"`
	Presentation string `json:"presentation,omitempty"`
	StdoutHash   string `json:"stdout_hash,omitempty"`
	StderrHash   string `json:"stderr_hash,omitempty"`
	WorkDir      string `json:"work_dir,omitempty"`
}

// Entry is a resolved stored result with paths to raw objects.
type Entry struct {
	ID         string
	Meta       Meta
	capsule    string
	stdoutPath string
	stderrPath string
}

// StdoutPath returns the path to the raw stdout object.
func (e *Entry) StdoutPath() string { return e.stdoutPath }

// StderrPath returns the path to the raw stderr object.
func (e *Entry) StderrPath() string { return e.stderrPath }

// Capsule returns the stored capsule text.
func (e *Entry) Capsule() (string, error) { return e.capsule, nil }

// UpdateMeta updates the in-memory metadata on the entry.
// For a persistent DB update, use Store.UpdateMeta(entry, meta).
func (e *Entry) UpdateMeta(meta Meta) error {
	e.Meta = meta
	return nil
}

// Store is a SQLite-backed result store rooted at a project directory.
type Store struct {
	root    string
	objsDir string
	db      *sql.DB
}

// New opens the store at the discovered project root (ACAP_ROOT > .acap ancestor > .git ancestor > cwd).
func New() (*Store, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("store: getwd: %w", err)
	}
	root := project.FindRoot(cwd)
	return Open(root)
}

// Open opens or creates the store at the given project root.
func Open(root string) (*Store, error) {
	if err := project.EnsureDirs(root); err != nil {
		return nil, fmt.Errorf("store: ensure dirs: %w", err)
	}
	dbPath := project.DBPath(root)
	db, err := sql.Open(driverName, dbPath+"?_busy_timeout=5000&_journal_mode=WAL&_foreign_keys=on")
	if err != nil {
		return nil, fmt.Errorf("store: open db: %w", err)
	}
	db.SetMaxOpenConns(1)
	s := &Store{
		root:    root,
		objsDir: project.ObjectsDir(root),
		db:      db,
	}
	if err := s.initSchema(); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store: init schema: %w", err)
	}
	return s, nil
}

// Close releases the database connection.
func (s *Store) Close() error {
	return s.db.Close()
}

// Root returns the project root directory.
func (s *Store) Root() string { return s.root }

// Save atomically stores a result. The Meta.ID field is generated by Save.
func (s *Store) Save(meta Meta, stdoutData, stderrData []byte, capsule string) (*Entry, error) {
	// Write raw objects.
	stdoutObj, err := s.writeObject(stdoutData)
	if err != nil {
		return nil, fmt.Errorf("store: write stdout object: %w", err)
	}
	stderrObj, err := s.writeObject(stderrData)
	if err != nil {
		return nil, fmt.Errorf("store: write stderr object: %w", err)
	}

	// Persist metadata in SQLite.
	argvJSON, err := json.Marshal(meta.Command)
	if err != nil {
		return nil, fmt.Errorf("store: marshal argv: %w", err)
	}
	queryStr := `INSERT INTO results (
	id, created_at, started_at, cwd, argv_json, exit_code, duration_ms, truncated,
	reducer, stdout_object, stderr_object, stdout_bytes, stderr_bytes,
	stdout_hash, stderr_hash, capsule,
	session_id, sequence, baseline_id, presentation, work_dir
	) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`
	createdAt := meta.CreatedAt.UTC().Format(time.RFC3339Nano)
	startedAt := meta.StartedAt.UTC().Format(time.RFC3339Nano)
	strArgvJSON := string(argvJSON)
	truncated := boolToInt(meta.Truncated)
	var id string
	for {
		id = generateID()
		meta.ID = id
		_, err = s.db.ExecContext(context.Background(), queryStr,
			id,
			createdAt,
			startedAt,
			meta.WorkDir,
			strArgvJSON,
			meta.ExitCode,
			meta.DurationMs,
			truncated,
			meta.Reducer,
			stdoutObj,
			stderrObj,
			meta.StdoutBytes,
			meta.StderrBytes,
			meta.StdoutHash,
			meta.StderrHash,
			capsule,
			meta.SessionID,
			meta.Sequence,
			meta.BaselineID,
			meta.Presentation,
			meta.WorkDir,
		)
		if err == nil {
			break
		} else {
			var sqliteErr *sqlite.Error
			if errors.As(err, &sqliteErr) {
				// Code 19 is SQLITE_CONSTRAINT
				// Extended code 1555 is SQLITE_CONSTRAINT_PRIMARYKEY
				if sqliteErr.Code() == 19 || sqliteErr.Code() == 1555 {
					continue
				}
			}
			return nil, fmt.Errorf("store: insert result: %w", err)
		}
	}

	return &Entry{
		ID:         id,
		Meta:       meta,
		capsule:    capsule,
		stdoutPath: filepath.Join(s.objsDir, stdoutObj),
		stderrPath: filepath.Join(s.objsDir, stderrObj),
	}, nil
}

// Open resolves an id to an Entry. Supports exact or unique prefix matching.
func (s *Store) Open(id string) (*Entry, error) {
	row := s.db.QueryRowContext(context.Background(), `
		SELECT id, created_at, started_at, cwd, argv_json, exit_code, duration_ms, truncated,
			reducer, stdout_object, stderr_object, stdout_bytes, stderr_bytes,
			stdout_hash, stderr_hash, capsule,
			session_id, sequence, baseline_id, presentation, work_dir
		FROM results WHERE id = ?`, id)

	entry, err := scanEntry(row, s.objsDir)
	if err == sql.ErrNoRows {
		// Try prefix match.
		return s.openByPrefix(id)
	}
	return entry, err
}

func (s *Store) openByPrefix(prefix string) (*Entry, error) {
	rows, err := s.db.QueryContext(context.Background(),
		`SELECT id FROM results WHERE id LIKE ? ORDER BY id`,
		prefix+"%")
	if err != nil {
		return nil, fmt.Errorf("store: prefix query: %w", err)
	}
	defer rows.Close()

	var matches []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err == nil {
			matches = append(matches, id)
		}
	}

	switch len(matches) {
	case 0:
		return nil, fmt.Errorf("store: result %q not found", prefix)
	case 1:
		return s.Open(matches[0])
	default:
		return nil, fmt.Errorf("store: ambiguous id prefix %q matches %v", prefix, matches)
	}
}

// List returns all entries sorted by created_at ascending.
func (s *Store) List() ([]*Entry, error) {
	rows, err := s.db.QueryContext(context.Background(), `
		SELECT id, created_at, started_at, cwd, argv_json, exit_code, duration_ms, truncated,
			reducer, stdout_object, stderr_object, stdout_bytes, stderr_bytes,
			stdout_hash, stderr_hash, capsule,
			session_id, sequence, baseline_id, presentation, work_dir
		FROM results ORDER BY created_at ASC`)
	if err != nil {
		return nil, fmt.Errorf("store: list: %w", err)
	}
	defer rows.Close()

	var out []*Entry
	for rows.Next() {
		e, err := scanEntry(rows, s.objsDir)
		if err != nil {
			continue // skip corrupt
		}
		out = append(out, e)
	}
	return out, nil
}

// Delete removes a result by id (exact or prefix).
func (s *Store) Delete(id string) error {
	e, err := s.Open(id)
	if err != nil {
		return err
	}

	// Remove objects first.
	_ = os.Remove(e.stdoutPath)
	_ = os.Remove(e.stderrPath)

	_, err = s.db.ExecContext(context.Background(), `DELETE FROM results WHERE id = ?`, e.ID)
	if err != nil {
		return fmt.Errorf("store: delete: %w", err)
	}
	return nil
}

// Cleanup removes results older than olderThan. Returns count removed.
func (s *Store) Cleanup(olderThan time.Duration) (int, error) {
	cutoff := time.Now().Add(-olderThan).UTC().Format(time.RFC3339Nano)

	// Fetch entries to delete (to clean objects).
	rows, err := s.db.QueryContext(context.Background(),
		`SELECT stdout_object, stderr_object FROM results WHERE created_at < ?`, cutoff)
	if err != nil {
		return 0, fmt.Errorf("store: cleanup query: %w", err)
	}
	var stdoutObjs, stderrObjs []string
	for rows.Next() {
		var so, se string
		if err := rows.Scan(&so, &se); err == nil {
			stdoutObjs = append(stdoutObjs, so)
			stderrObjs = append(stderrObjs, se)
		}
	}
	rows.Close()

	// Delete rows.
	res, err := s.db.ExecContext(context.Background(),
		`DELETE FROM results WHERE created_at < ?`, cutoff)
	if err != nil {
		return 0, fmt.Errorf("store: cleanup delete: %w", err)
	}

	// Remove object files.
	for _, obj := range stdoutObjs {
		_ = os.Remove(filepath.Join(s.objsDir, obj))
	}
	for _, obj := range stderrObjs {
		_ = os.Remove(filepath.Join(s.objsDir, obj))
	}

	n, _ := res.RowsAffected()
	return int(n), nil
}

// UpdateMeta updates a stored result's metadata.
func (s *Store) UpdateMeta(entry *Entry, meta Meta) error {
	_, err := s.db.ExecContext(context.Background(), `
		UPDATE results SET
			session_id=?, sequence=?, baseline_id=?, presentation=?,
			stdout_hash=?, stderr_hash=?, work_dir=?
		WHERE id=?`,
		meta.SessionID, meta.Sequence, meta.BaselineID, meta.Presentation,
		meta.StdoutHash, meta.StderrHash, meta.WorkDir,
		entry.ID,
	)
	if err != nil {
		return fmt.Errorf("store: update meta: %w", err)
	}
	entry.Meta = meta
	return nil
}

// --- Stats methods ---

// RecordRun records a run invocation with optional session stats.
func (s *Store) RecordRun(raw, stateless, stateful int, presentation string) error {
	return s.incrStats(map[string]int64{
		"commands":        1,
		"raw_bytes":       int64(raw),
		"ret_bytes":       int64(stateful),
		"stateless_bytes": int64(stateless),
		"stateful_bytes":  int64(stateful),
		"unchanged_count": presentationCount(presentation, "unchanged"),
		"delta_count":     presentationCount(presentation, "delta"),
		"full_count":      presentationCount(presentation, "full"),
	})
}

// RecordShow records a show invocation.
func (s *Store) RecordShow(retBytes int) error {
	return s.incrStats(map[string]int64{
		"show_calls":     1,
		"show_ret_bytes": int64(retBytes),
	})
}

// RecordRaw records a raw invocation.
func (s *Store) RecordRaw(retBytes int) error {
	return s.incrStats(map[string]int64{
		"raw_calls":     1,
		"raw_ret_bytes": int64(retBytes),
	})
}

// LoadStats returns accumulated statistics from the store.
func (s *Store) LoadStats() (*stats.Stats, error) {
	rows, err := s.db.QueryContext(context.Background(), `SELECT key, value FROM stats`)
	if err != nil {
		return &stats.Stats{}, nil
	}
	defer rows.Close()

	kv := make(map[string]int64)
	for rows.Next() {
		var k string
		var v int64
		if err := rows.Scan(&k, &v); err == nil {
			kv[k] = v
		}
	}

	return &stats.Stats{
		Commands:          kv["commands"],
		RawBytes:          kv["raw_bytes"],
		RetBytes:          kv["ret_bytes"],
		ShowCalls:         kv["show_calls"],
		ShowRetBytes:      kv["show_ret_bytes"],
		RawCalls:          kv["raw_calls"],
		RawRetBytes:       kv["raw_ret_bytes"],
		UnchangedCount:    kv["unchanged_count"],
		DeltaCount:        kv["delta_count"],
		FullFallbackCount: kv["full_count"],
		StatelessBytes:    kv["stateless_bytes"],
		StatefulBytes:     kv["stateful_bytes"],
	}, nil
}

func (s *Store) incrStats(kv map[string]int64) error {
	tx, err := s.db.BeginTx(context.Background(), nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	for k, v := range kv {
		if v == 0 {
			continue
		}
		_, err := tx.ExecContext(context.Background(), `
			INSERT INTO stats(key, value) VALUES(?,?)
			ON CONFLICT(key) DO UPDATE SET value = value + excluded.value`,
			k, v)
		if err != nil {
			return err
		}
	}
	return tx.Commit()
}

// --- Internals ---

func (s *Store) writeObject(data []byte) (string, error) {
	var objID string
	var path string
	for {
		b := rand.Uint64()
		objID = fmt.Sprintf("%08x", b)

		path = filepath.Join(s.objsDir, objID)
		_, err := os.Stat(path)
		if err != nil {
			break
		}
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return "", fmt.Errorf("store: write object tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return "", fmt.Errorf("store: rename object: %w", err)
	}
	return objID, nil
}

type scanner interface {
	Scan(...interface{}) error
}

func scanEntry(s scanner, objsDir string) (*Entry, error) {
	var (
		id, createdAt, startedAt, cwd, argvJSON string
		exitCode, durationMs, truncatedInt      int64
		reducer, stdoutObj, stderrObj           string
		stdoutBytes, stderrBytes                int64
		stdoutHash, stderrHash, capsule         string
		sessionID, baselineID, presentation     string
		workDir                                 string
		sequence                                int64
	)

	err := s.Scan(
		&id, &createdAt, &startedAt, &cwd, &argvJSON, &exitCode, &durationMs, &truncatedInt,
		&reducer, &stdoutObj, &stderrObj, &stdoutBytes, &stderrBytes,
		&stdoutHash, &stderrHash, &capsule,
		&sessionID, &sequence, &baselineID, &presentation, &workDir,
	)
	if err != nil {
		return nil, err
	}

	var argv []string
	_ = json.Unmarshal([]byte(argvJSON), &argv)

	created, _ := time.Parse(time.RFC3339Nano, createdAt)
	started, _ := time.Parse(time.RFC3339Nano, startedAt)

	meta := Meta{
		ID:           id,
		Command:      argv,
		ExitCode:     int(exitCode),
		StartedAt:    started,
		DurationMs:   durationMs,
		StdoutBytes:  stdoutBytes,
		StderrBytes:  stderrBytes,
		Reducer:      reducer,
		CreatedAt:    created,
		Truncated:    truncatedInt != 0,
		SessionID:    sessionID,
		Sequence:     int(sequence),
		BaselineID:   baselineID,
		Presentation: presentation,
		StdoutHash:   stdoutHash,
		StderrHash:   stderrHash,
		WorkDir:      workDir,
	}

	return &Entry{
		ID:         id,
		Meta:       meta,
		capsule:    capsule,
		stdoutPath: filepath.Join(objsDir, stdoutObj),
		stderrPath: filepath.Join(objsDir, stderrObj),
	}, nil
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func presentationCount(presentation, match string) int64 {
	if presentation == match {
		return 1
	}
	return 0
}

func generateID() string {
	b := rand.Uint32() & 0x00ffffff
	return fmt.Sprintf("%06x", b)
}
