// Package store provides persistent result storage for acap.
//
// Results are stored in ~/.cache/agentcap/results/<id>/ with atomic creation
// via a temporary directory rename.
package store

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Meta holds the metadata saved alongside each result.
type Meta struct {
	ID          string    `json:"id"`
	Command     []string  `json:"command"`
	ExitCode    int       `json:"exit_code"`
	StartedAt   time.Time `json:"started_at"`
	DurationMs  int64     `json:"duration_ms"`
	StdoutBytes int64     `json:"stdout_bytes"`
	StderrBytes int64     `json:"stderr_bytes"`
	Reducer     string    `json:"reducer"`
	CreatedAt   time.Time `json:"created_at"`
	Truncated   bool      `json:"truncated"`
	// Phase 3 fields (all omitempty for backwards compatibility)
	SessionID    string `json:"session_id,omitempty"`
	Sequence     int    `json:"sequence,omitempty"`
	BaselineID   string `json:"baseline_id,omitempty"`
	Presentation string `json:"presentation,omitempty"`
	StdoutHash   string `json:"stdout_hash,omitempty"`
	StderrHash   string `json:"stderr_hash,omitempty"`
	WorkDir      string `json:"work_dir,omitempty"`
}

// Entry is a resolved result directory.
type Entry struct {
	ID   string
	Dir  string
	Meta Meta
}

// StdoutPath returns the absolute path to the stored stdout file.
func (e *Entry) StdoutPath() string {
	return filepath.Join(e.Dir, "stdout")
}

// StderrPath returns the absolute path to the stored stderr file.
func (e *Entry) StderrPath() string {
	return filepath.Join(e.Dir, "stderr")
}

// CapsulePath returns the absolute path to the stored capsule file.
func (e *Entry) CapsulePath() string {
	return filepath.Join(e.Dir, "capsule")
}

// Capsule reads and returns the contents of the capsule file.
func (e *Entry) Capsule() (string, error) {
	data, err := os.ReadFile(e.CapsulePath())
	if err != nil {
		return "", fmt.Errorf("store: read capsule %s: %w", e.ID, err)
	}
	return string(data), nil
}

// UpdateMeta rewrites meta.json with updated metadata.
func (e *Entry) UpdateMeta(meta Meta) error {
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return fmt.Errorf("store: marshal meta: %w", err)
	}
	tmp := filepath.Join(e.Dir, "meta.json.tmp")
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return fmt.Errorf("store: write meta tmp: %w", err)
	}
	dst := filepath.Join(e.Dir, "meta.json")
	if err := os.Rename(tmp, dst); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("store: rename meta: %w", err)
	}
	e.Meta = meta
	return nil
}

// Store is a filesystem-backed result store.
type Store struct {
	dir string // base dir, e.g. ~/.cache/agentcap
}

// New creates a Store rooted at os.UserCacheDir()/agentcap, creating
// the necessary subdirectories.
func New() (*Store, error) {
	cacheDir, err := os.UserCacheDir()
	if err != nil {
		return nil, fmt.Errorf("store: cannot determine cache dir: %w", err)
	}
	base := filepath.Join(cacheDir, "agentcap")
	if err := os.MkdirAll(filepath.Join(base, "results"), 0o700); err != nil {
		return nil, fmt.Errorf("store: cannot create results dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(base, "tmp"), 0o700); err != nil {
		return nil, fmt.Errorf("store: cannot create tmp dir: %w", err)
	}
	return &Store{dir: base}, nil
}

// Save atomically stores a result. The Meta.ID field is generated by Save
// (any caller-provided ID is overwritten). Returns the created Entry.
func (s *Store) Save(meta Meta, stdoutData, stderrData []byte, capsule string) (*Entry, error) {
	id, err := generateID()
	if err != nil {
		return nil, fmt.Errorf("store: generate id: %w", err)
	}
	meta.ID = id

	// Create temp dir.
	tmpID, err := generateID()
	if err != nil {
		return nil, fmt.Errorf("store: generate tmp id: %w", err)
	}
	tmpDir := filepath.Join(s.dir, "tmp", tmpID)
	if err := os.MkdirAll(tmpDir, 0o700); err != nil {
		return nil, fmt.Errorf("store: create tmp dir: %w", err)
	}

	// Write all files into tmpDir.
	metaData, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		_ = os.RemoveAll(tmpDir)
		return nil, fmt.Errorf("store: marshal meta: %w", err)
	}
	files := []struct {
		name string
		data []byte
	}{
		{"meta.json", metaData},
		{"stdout", stdoutData},
		{"stderr", stderrData},
		{"capsule", []byte(capsule)},
	}
	for _, f := range files {
		path := filepath.Join(tmpDir, f.name)
		if err := os.WriteFile(path, f.data, 0o600); err != nil {
			_ = os.RemoveAll(tmpDir)
			return nil, fmt.Errorf("store: write %s: %w", f.name, err)
		}
	}

	// Atomic rename into results/.
	finalDir := filepath.Join(s.dir, "results", id)
	if err := os.Rename(tmpDir, finalDir); err != nil {
		_ = os.RemoveAll(tmpDir)
		return nil, fmt.Errorf("store: rename to results: %w", err)
	}

	return &Entry{ID: id, Dir: finalDir, Meta: meta}, nil
}

// Open resolves an id to an Entry. If the id is an exact match it is returned
// directly. Otherwise all result directory names are scanned for a unique
// prefix match. An ambiguous prefix returns an error.
func (s *Store) Open(id string) (*Entry, error) {
	resultsDir := filepath.Join(s.dir, "results")

	// Exact match fast-path.
	exactDir := filepath.Join(resultsDir, id)
	if fi, err := os.Stat(exactDir); err == nil && fi.IsDir() {
		return loadEntry(exactDir, id)
	}

	// Prefix scan.
	entries, err := os.ReadDir(resultsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("store: result %q not found", id)
		}
		return nil, fmt.Errorf("store: list results: %w", err)
	}

	var matches []string
	for _, de := range entries {
		if de.IsDir() && strings.HasPrefix(de.Name(), id) {
			matches = append(matches, de.Name())
		}
	}

	switch len(matches) {
	case 0:
		return nil, fmt.Errorf("store: result %q not found", id)
	case 1:
		dir := filepath.Join(resultsDir, matches[0])
		return loadEntry(dir, matches[0])
	default:
		return nil, fmt.Errorf("store: ambiguous id prefix %q matches %v", id, matches)
	}
}

// List returns all stored entries sorted by created_at ascending.
func (s *Store) List() ([]*Entry, error) {
	resultsDir := filepath.Join(s.dir, "results")
	entries, err := os.ReadDir(resultsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("store: list results: %w", err)
	}

	var out []*Entry
	for _, de := range entries {
		if !de.IsDir() {
			continue
		}
		dir := filepath.Join(resultsDir, de.Name())
		e, err := loadEntry(dir, de.Name())
		if err != nil {
			continue // skip corrupt entries
		}
		out = append(out, e)
	}
	return out, nil
}

// Delete removes a result by id (exact or prefix).
func (s *Store) Delete(id string) error {
	e, err := s.Open(id)
	if err != nil {
		return err
	}
	if err := os.RemoveAll(e.Dir); err != nil {
		return fmt.Errorf("store: delete %s: %w", id, err)
	}
	return nil
}

// Cleanup removes complete results older than olderThan. Returns the count
// of removed entries.
func (s *Store) Cleanup(olderThan time.Duration) (int, error) {
	entries, err := s.List()
	if err != nil {
		return 0, err
	}
	cutoff := time.Now().Add(-olderThan)
	removed := 0
	for _, e := range entries {
		if e.Meta.CreatedAt.Before(cutoff) {
			if err := os.RemoveAll(e.Dir); err == nil {
				removed++
			}
		}
	}
	return removed, nil
}

// loadEntry reads meta.json from dir and returns an Entry.
func loadEntry(dir, id string) (*Entry, error) {
	metaPath := filepath.Join(dir, "meta.json")
	data, err := os.ReadFile(metaPath)
	if err != nil {
		return nil, fmt.Errorf("store: read meta for %s: %w", id, err)
	}
	var meta Meta
	if err := json.Unmarshal(data, &meta); err != nil {
		return nil, fmt.Errorf("store: parse meta for %s: %w", id, err)
	}
	return &Entry{ID: id, Dir: dir, Meta: meta}, nil
}

// marshalJSON is an alias used by tests in the same package.
func marshalJSON(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

// generateID returns a random 6-hex-char string using crypto/rand.
func generateID() (string, error) {
	b := make([]byte, 3)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
